overtone/overtone

src/overtone/music/rhythm.clj

As it stood, the metronome could become inconsistent when multiple threads are making changes to it at the same time, because it was using atoms for its internal state, and atoms only provide isolated consistency.
Since changes sometimes need to be made to multiple state items in a coordinated fashion, the metronome needs to instead use refs and Clojure's software transactional memory features. I discovered this problem because I am synchronizing a metronome to the BPM of DJ software using MIDI clock pulses, while also allowing the user to beat jump, or change attributes like beats-per-bar.

Keep metronome consistent under multithreading

---

src/overtone/api.clj
src/overtone/sc/machinery/ugen/metadata/delay.clj
src/overtone/sc/machinery/ugen/metadata/extras/README.md
src/overtone/sc/machinery/ugen/metadata/extras/vbap.clj
src/overtone/sc/machinery/ugen/specs.clj
src/overtone/sc/vbap.clj

The patches add support for the del-tap-wr, del-tap-rd and vbap UGens. The del-tap ugens are simply added in the metadata, the vbap is added to metatdata/extras and a complete port of the vbap-speaker-array calculation of sclang is added under overtone/src/sc/vbap.clj. Maybe that should get relocated, I wasn't sure where to put it.
The vbap code is extensively commented and examples are provided in the docstrings.

added del-tap-wr, del-tap-rd and vbap.

---

src/overtone/helpers/file.clj
src/overtone/samples/freesound.clj

Hi Sam,
This is more to start a discussion than to accept as is. I noticed that the Freesound API used by Overtone is now completely disabled on the Freesound website, which enforces the new version APIv2.
- a big inconvenience of the new version: the user has to authorize the application in order to get an access token -- does this step have to be interactive and through a browser?

a first try at porting to APIv2 of Freesound

---

src/overtone/sc/sample.clj

As suggested by @ormf in #318, I changed the default release to 0 for mono-partial-player and stereo-partial-player.
This fixes the issue with free sound samples being triggered twice.

fix #318 - prevent double trigger of freesound samples

---

src/overtone/repl/inst.clj
src/overtone/studio/inst.clj

Clojure 1.9 introduces clojure.core/Inst and clojure.core/inst?, and these clash
with overtone.studio.inst/Inst and overtone.studio.inst/inst?.
This patch adds `:refer-clojure :exclude [Inst inst?]`, you still get warnings
when requiring overtone.live, but it no longer blows up.

Clojure 1.9 compat: exclude Inst and inst?

---

src/overtone/live.clj

Sorry, misssed this one the first time. Now you can `(require 'overtone.live)` without warnings.

Exclude inst? from overtone.live as well

---

src/overtone/samples/freesound/url.clj
src/overtone/sc/foundation_groups.clj

Since clojure.specs for `ns` were added in the 1.9.0 alphas requiring overtone failed at runtime due to:
```
ExceptionInfo Call to clojure.core/ns did not conform to spec:
In: [1] val: ((use [overtone.libs.deps :only [on-deps satisfy-deps]])) fails at: [:args] predicate: (cat :docstring (? string?) :attr-map (? map?) :clauses :clojure.core.specs/ns-clauses),  Extra input
```
This PR replaces `use` and `import` to their keyword forms in `ns` declarations.

Clojure 1.9.0 compatibility - use :use and :import keyword forms in ns declarations

---

src/overtone/algo/chance.clj

This fixes issues #381.
`overtone.algo.chance/weighted-sum` now uses `==` to check probabilities sum to 1.

Fixed #381. weighted-sum now uses == to check probabilities sum to 1

---

src/overtone/helpers/file.clj

When I evaluate the following code, Overtone will not stop downloading (until 50-times) and I add an  exception clause for java.io.FileNotExcepiton.
`(def dirty-kick (freesound 30669))` in https://github.com/overtone/overtone/blob/master/src/overtone/examples/getting_started/pragpub-article.clj#L178

Abort immediately after received 'File not found'

---

src/overtone/helpers/lib.clj

Previously, code only checked inside PROGRAMFILES(X86) even if both
environment variables and directories exist. 
The new code checks in both environment variables and associated 
directories. Code is robust and will work even if the environment 
variables don't exist, or the directories don't exist.
Note that in my case, both `PROGRAMFILES(X86)` and `PROGRAMFILES` 
exist, but SuperCollider is only installed in the latter.

Search for SuperCollider in more places on Windows.

---

src/overtone/sc/machinery/server/connection.clj

When the `error?` is false, nothing was logged.

Fix log condition

---

src/overtone/music/rhythm.clj

I am writing a lighting control framework in Clojure, and the Overtone metronome object is almost perfect, but I needed a way to be able to tell how far into a beat or bar we have reached at the current moment (for doing things like pulsing lights in time to the music). This request adds that capability, as well as simplifying the namespace declaration to pull in only the specific function that it needs. Feel free to omit that second commit if you otherwise like this pull request.

Add functions to determine phase within beat/bar

---

src/overtone/studio/mixer.clj

The lack of parens around this assoc call causes definst/inst to throw an exception when called after the server is killed then started again. This error causes studio* to have the wrong shape after the server is booted a second time. The change in state before and after the reboot can be seen here:
```clojure
user=> (definst drum [] (sin-osc 440))
#<instrument: drum>
user=> (:group (get (:instruments @studio*) "drum"))
#<synth-group[live]: Inst drum Container 33>
user=> (kill-server)
:server-killed
user=> (boot-external-server)
...
user=> (definst drum [] (sin-osc 440))
CompilerException java.lang.IllegalArgumentException: No implementation of method: :to-sc-id of protocol: #'overtone.sc.node/to-sc-id* found for class: java.lang.String, compiling:(form-init33334487881954785.clj:1:1) …
```

Add missing parens in assoc call in studio/mixer

---

src/overtone/music/pitch.clj

Fixes (again) #428.
The original parsing that used `(int ...)` doesn't seem to like strings from what I can tell.
My apologizes if I made a mistake somewhere in this, I'm a bit rushed ATM.

Parse the octave string with `Integer/parseInt`

---

src/overtone/samples/piano.clj

This change seems necessary to me to be able to load the piano samples.

remove cruft, causing a syntax error

---

src/overtone/sc/buffer.clj

Should check against n-samples, as there may be more than 1 channel.

Fix size check

---

src/overtone/sc/machinery/server/args.clj

The previous logic in the modified code compares the major and minor
portions of the supercollider version by converting the version string
to a floating point number and comparing it to a numeric constant. This
comparison breaks when upgrading to supercollider `3.10` because `(< 3.6
3.10)` is false.
This commit changes the comparison to use a sequence of integers in a
vector, such as `[3 10]`. This data structure can be compared using the
`compare` function resulting in semantics that match how semantic
versions are compared.
```
(neg? (compare [3 6] [3 5]))  ; => false
(neg? (compare [3 6] [3 6]))  ; => false
(neg? (compare [3 6] [3 9]))  ; => true
(neg? (compare [3 6] [3 10])) ; => true
```

Fix broken version comparison in args/SC-ARG-INFO

---

src/overtone/osc/peer.clj

I ran into an issue when using a listener/handler with the osc-server. Turns out, due to my being on a non-internet connected network, `INetAddress` was trying to perform a reverse name lookup on the server that had sent me the OSC packet. This was then hanging until the timeout was reached.
Using `#getHostString` will not perform a lookup, and instead just use the hostname/ip the address was initialized with.
I realize that this isn't (technically) a backwards compatible change, so let me know if I should add a flag to choose between the types of behavior.

OSC: Don't do reverse name lookup when handling packets

---

deps.edn

without this change I get
```
Error building classpath. Library badigeon/badigeon has sha and tag that point to different commits
```
when trying to start a repl with overtone as a dependency.
Might also be nice to get a release out with this + https://github.com/overtone/overtone/commit/02f8cdd2817bf810ff390b6f91d3e84d61afcc85 because I spent a long while battling
```
Unhandled clojure.lang.Compiler$CompilerException
Syntax error compiling at (badigeon/bundle.clj:1:1).
{:clojure.error/phase :compile-syntax-check, :clojure.error/line 1, :clojure.error/column 1, :clojure.error/source "badigeon/bundle.clj"}
Unhandled java.io.FileNotFoundException
Could not locate clojure/tools/deps/alpha/reader__init.class, clojure/tools/deps/alpha/reader.clj or clojure/tools/deps/alpha/reader.cljc on …
```

remove `:tag` from badigeon/badigeon lib dep; it mismatches the git sha

---

src/overtone/samples/freesound.clj

This subtle change restores Freesound download functionality and partially resolves issue #475.

use canonical URL for freesound API

---

src/overtone/config/store.clj
src/overtone/libs/asset.clj

This fix addresses issue  #486  and allows me to use the sampled-piano on windows. 
The files end up being stored in weird places. For example sample 148530 ends up as a wav file store here:
- ~/.overtone/assets/freesound.org-apiv2-sounds-148530-download----208323509/     
PIANO_LOUD_DB5.wav  
and a json file that describes it store in another directory                                                                                                                                                             
~/.overtone/assets/freesound.org-apiv2-sounds-148530-formatjson---4716015:      
148530          
Looking at the code, I think the same weirdness happens in linux too with the current version.

Fix window paths to allow downloading samples

---

project.clj

I had to remove this option to be able to start the repl with lein.
The concurrent mark sweep (CMS) garbage collector was removed in java 14
see https://en.wikipedia.org/wiki/Concurrent_mark_sweep_collector

removed obsolete JVM option CMSConcurrentMTEnabled

---

README.md

This is a total nit/boyscout correction. `clj-kondo` advised I fully qualify the namespace for the dependency.

Qualify the overtone ns in lein example

---

src/overtone/examples/instruments/slide-guitar.clj
src/overtone/synth/stringed.clj

This implements a functions into the stringed-synth that enables it to slide a string from fret to fret.
It needs some non-public functions from the string-synth therefore I put in in there.

Slide-Guitar example and functions for stringed.clj

---

CHANGELOG.md
src/overtone/libs/deps.clj

Fixes an issue where Clojure fails to resolves the Thread/sleep call on newer JVMs.
Closes #497

Cast timeout-ms/wait-time to long

---

src/overtone/helpers/lib.clj
src/overtone/samples/freesound.clj
src/overtone/sc/util.clj
src/overtone/synth/stringed.clj

Besides the versions with a fixed number of arguments, there is one final one that takes an array as its final argument (i.e. a Java varargs function). Take that into account so we don't run into AbstractMethod error when it gets called.
Also deals with an issue using an unquoted `abs` in the stringed instrument, and some minor namespace cleanup.

Fix 21-arity version of clojure.lang.IFn

---

CHANGELOG.md
docs/config.clj
src/overtone/config/file_store.clj
src/overtone/config/store.clj
src/overtone/music/pitch.clj
src/overtone/sc/envelope.clj
src/overtone/sc/machinery/ugen/fn_gen.clj
src/overtone/sc/machinery/ugen/metadata/binaryopugen.clj
src/overtone/sc/machinery/ugen/special_ops.clj
src/overtone/sc/ugens.clj

Since Clojure 1.11 abs is a function in clojure, and thus clashes with the abs UGen. By marking it as a numerical function that's less of a problem. 
Also bring back lin-env as an alias for lin, and (sort of) document `:force-ugen`.

Improve how we deal with `abs`

---

src/overtone/libs/event.clj
test/overtone/event_test.clj

`(event)` doesn't use `apply` when using `overtone.libs.handlers`, but `(sync-event)` does. I've got a feeling it shouldn't be there.

Possible bug in sync-event

---

.gitignore
CHANGELOG.md
LICENSE
README.md
bin/proj
deps.edn
docs/cheatsheet/overtone-cheat-sheet.tex
pom.xml
src/overtone/byte_spec.clj
src/overtone/examples/timing/internal_sequencer.clj
src/overtone/helpers/file.clj
src/overtone/libs/asset.clj
src/overtone/libs/counters.clj
src/overtone/midi.clj
src/overtone/music/drums.clj
src/overtone/music/rhythm.clj
src/overtone/music/time.clj
src/overtone/samples/freesound.clj
src/overtone/sc/buffer.clj
src/overtone/sc/machinery/server/connection.clj
src/overtone/sc/machinery/synthdef.clj
src/overtone/sc/machinery/ugen/defaults.clj
src/overtone/sc/machinery/ugen/metadata/extras/loopbuf.clj
src/overtone/sc/machinery/ugen/specs.clj
src/overtone/sc/node.clj
src/overtone/sc/synth.clj
src/overtone/studio/inst.clj
src/overtone/studio/midi.clj
src/overtone/version.clj

See CHANGELOG
- New `loop-buf` UGen, for looping samples (part of sc3-plugins "extras")
- Watch for MIDI device plug/unplug, so that adding a device doesn't require a
restart. These will also emit events: `:midi-device-connected` /
`:midi-device-disconnected` / `:midi-receiver-connected` /
`:midi-receiver-disconnected`
- Add `buffer-alloc-read-channel`, like `buffer-alloc-read` (instruct the SC
server to load a sound file), but only reads a single channel. Corresponds
with the `/b_allocReadChannel` OSC message.
- Make sure we print the correct version when booting
- Fix the license information in pom.xml (MIT)
- Handle a 401 response from Freesound by asking for a new token, instead of retrying
- Allow writing buffers that are bigger than MAX-OSC-SAMPLES
- Reuse param `:value` atoms when …

Changes for next major release, 0.13.x

---

src/overtone/examples/compositions/clapping_music.clj

This PR fixes issues #463 and #465 which prevented `overtone.examples.compositions.clapping-music` from being playable.
The playback is still 'clicky' due to sample playback, and I'm not sure how to fix this. I tried using `load-sample` and `play-buf` as suggested [here](https://github.com/overtone/overtone/issues/421) but I couldn't find a way to change the volume of each sample playback.

Fixed broken freesound link and broken args

---

src/overtone/sc/machinery/ugen/specs.clj

This fixes #515.
```clj
(comment
(o/connect-external-server)
(o/defsynth rev-perc []
(let [sig (-> (o/sin-osc 200)
(o/pan2:ar)
(* 0.2 (o/env-gen (o/env-perc)))
(o/free-verb 0.5 3))]
(o/free-self (* (o/detect-silence (+ sig (o/impulse 0)))))
(o/out 0 sig)))
(def node (rev-perc))
;; after a while
(println node) ;; #<synth-node[destroyed]: external.dev/rev-perc 107>  
)
```

Allow free-self to take audio-rate signals (#515)

---

src/overtone/examples/getting_started/basic.clj

- The first iteration of the do loop gives a frequency of 0
- The first iteration is now at 220 hz instead

Fix foo and foo-timed example

---

src/overtone/synth/stringed.clj

Changes incorrect "pluck-strings" to "pick-string" in docs. 
Resolves #521

Update stringed.clj to fix incorrect function name in docstrings

---

src/overtone/samples/freesound.clj

Close #337 
This adds an additional dialog box in case stdin doesn't work for Freesound auth.
I have no idea if the stdin flow still works with these changes since I've never successfully got it to work. You can test it by removing the `~/.overtone/user-store.edn` file and calling `((requiring-resolve 'overtone.samples.freesound/authorization-instructions))`.

Close #337: open dialog box for Freesound auth

---

src/overtone/music/pitch.clj

This docstring seems to display the output of `:a3 :minor` instead of `:a4 :minor`.

Fix `chord` docstring

---

src/overtone/sc/synth.clj

This keyword seems to be used by `callable-map`.

Fix toString overrides for overtone.helpers.lib/callable-map

---

src/overtone/libs/boot_msg.clj
src/overtone/live.clj

I was curious if AOT compilation works after reading https://github.com/overtone/overtone/issues/481, and it does. This makes compilation a little more flexible so it can be performed without SC booting. I didn't test removing SC altogether so I'm not sure if compilation requires SC to be accessible (but it sounds useful if it doesn't).
This can be tested by creating a `classes` directory at the root of this repo:
```clojure
user=> (compile 'overtone.live)
--> Compiling Overtone...
--> (use 'overtone.live :reload) or restart JVM to use SuperCollider after compilation
overtone.live
user=> (use 'overtone.live) ;; no effect
nil
user=> (use 'overtone.live :reload) ;; triggers __AUTO-BOOT__
--> Booting external SuperCollider server...
```

Don't start SC during compilation

---

src/overtone/helpers/gui.clj
src/overtone/helpers/ns.clj
src/overtone/samples/freesound.clj
src/overtone/studio/event.clj

octave-note was being interned twice from different namespaces into the api namespaces. This fixes that particular problem, and adds checks to detect similar regressions in the future.

Close #528: fix octave-note, detect similar issues

---

CHANGELOG.md
src/overtone/examples/compositions/funk.clj
src/overtone/inst/synth.clj
src/overtone/music/rhythm.clj
src/overtone/music/time.clj
src/overtone/protocols.clj
src/overtone/sc/foundation_groups.clj
src/overtone/sc/machinery/server/connection.clj
src/overtone/sc/node.clj
src/overtone/sc/sample.clj
src/overtone/studio/event.clj

- Pattern library: make patterns more easily redefinable while maintaining the
same relative position, for smoother live updates
- Accept `:-` as a rest note, in addition to `:_` and `:rest`
- Recognize samples in the pattern player, so things like `:amp` work
- Metronome: also accept `:start` and `:bar-start`, instead of just `:bpm`
- Allow the default `at-at` threadpool to be overridden by a dynvar
(`*current-pool*`)
- `:sc-path` in `~/.overtone/config.clj` can now be a vector instead of a
string, for passing additional arguments
- `grunge-bass` : make the amp parameter do something
- Changed the implementation of the sample player to a more basic version based
on `play-buf`, since the old version caused clicks at the end of the sample.
This does mean currently looping is broken.

Pattern library and other improvements

---

src/overtone/synth/stringed.clj

The addition of the `'` suffix to the name may have been accidental or may have been to avoid a linter warning that `distort` shadows the `distort` fn name. Running clj-kondo with linter configuration set up in https://github.com/overtone/overtone/pull/493 does not show corrected name as an error or warning.
This is a (tiny) breaking change that makes the existing guitar-synth or slide-guitar examples work correctly and makes the parameter less unusual.

Change `distort'` parameter to `distort` to match example uses

---

src/overtone/algo/chance.clj
src/overtone/helpers/doc.clj
src/overtone/helpers/file.clj
src/overtone/helpers/lib.clj
src/overtone/libs/event.clj
src/overtone/libs/handlers.clj
src/overtone/midi.clj
src/overtone/music/pitch.clj
src/overtone/osc/encode.clj
src/overtone/osc/peer.clj
src/overtone/osc/util.clj
src/overtone/repl/debug.clj
src/overtone/sc/buffer.clj
src/overtone/studio/event.clj

Close #537
I was conservative about autoboxing warnings based on my reading of https://clojure.org/reference/java_interop#optimization
The remaining warnings are fixed by https://github.com/overtone/at-at/pull/26
overtone.studio.event doesn't compile so I fixed it. I also fixed a different bug where a list was being tested for `integer?`.
```clojure
user=> (set! *warn-on-reflection* true)
true
user=> (use 'overtone.live)
--> Loading Overtone...
Reflection warning, overtone/at_at.clj:15:3 - reference to field printStackTrace can't be resolved.
Reflection warning, overtone/at_at.clj:211:16 - call to java.util.concurrent.ScheduledThreadPoolExecutor ctor can't be resolved.
```

Fix reflection warnings

---

CHANGELOG.md
src/overtone/sc/machinery/ugen/metadata/binaryopugen.clj
src/overtone/sc/machinery/ugen/special_ops.clj
test/overtone/sc/ugen_collide_test.clj

Close #536 
The original problem was that the `and/or` ugens "overload" to the Clojure macros, which doesn't work at all (even if it made sense).
I looked into these operators in SC and they're actually bitwise operators, which we already have names for in Clojure. Maybe we could use them?
By renaming the vars, we exchange the macro overloading with function overloading like all the other colliding ugens.
It's hard to tell if these breaking changes are worth it, my thoughts:
`and` and `or` were completely broken for numeric arguments, but probably worked fine as ugens. There's a third case where someone intended to use `clojure.core/{and,or}` but ended up forcing a ugen due to non-numeric args, which is more worrying.
`xor` always worked fine, but it was hard to resist overloading …

Rename {and,or,xor} ugens to bit-{and,or,xor}

---

CHANGELOG.md
src/overtone/sc/ugen_collide.clj
src/overtone/sc/ugens.clj

I like referring to these ugens explicitly so I can access their docs and refactor them into helpers without having to think about `with-overloaded-ugens`.

Support explicit `require` of `overtone.sc.ugen-collide`

---

src/overtone/sc/synth.clj

We may want to defined a synth like below
```clojure
(defsynth-load directional
(str "test-resources" "/directional.scsyndef"))
```
Which was throwing an exception because it didn't understand the unevaluated `(str ...)` as a file path.
This fixes it.
The reason for using `defsynth-load` instead of `synth-load` is so we can have a `defsynth`-like metadata attached to the var.

Fix `defsynth-load`

---

src/overtone/studio/event.clj

The pattern library docs claim support for setting `:start-time` or `:beat` on an event.
This change updates the `next-beat` calculation to include peeking at the next event to schedule it appropriately, falling back to `(+ beat dur)`.
The reset of the clock to 0 when no players are active causes problems. It is noted in `FIXME` about starting multiple players. In my case, since I'm setting event times based on the clock, resetting it wreaks havoc. I hope that going forward it makes sense for the pattern lib to take a read only approach to the clock. Who knows what else a client of the lib might be using their clock for?
I know you're in the middle of edits to pattern lib and I don't want to step on your toes, @plexus, but this is an issue I ran into.

Enable event `:beat` and `:start time`

---

CHANGELOG.md
src/overtone/sc/machinery/ugen/fn_gen.clj
test/overtone/sc/ugen_collide_test.clj

Sometime in the last 10+ years Clojure explicitly supported vars called `/`. `with-overloaded-ugen` wraps with `(let [/ binary-div-op] ..)`, so most users will not notice this.

Rename `binary-div-op` ugen var to `/`

---

src/overtone/api.clj
src/overtone/studio/aux_bus.clj

Close #561
Cannot have a file named aux.clj on Windows.
https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions
> Do not use the following reserved names for the name of a file:
> 
> CON, PRN, **AUX**, NUL, COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, COM¹, COM², COM³, LPT0, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9, LPT¹, LPT², and LPT³.
> 
> **Also avoid these names followed immediately by an extension**; for example, NUL.txt and NUL.tar.gz are both equivalent to NUL. For more information, see [Namespaces](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces).

Window compat: rename overtone.studio.aux => overtone.studio.aux-bus

---

src/overtone/osc/dyn_vars.clj
src/overtone/sc/server.clj
src/overtone/synth/stringed.clj

- Added `at-offset`, including new dynamic var to hold scheduled time of enclosing `at`, if any.
- `pluck-string`, `strum-string`, and `slide-string` now work correctly with `at`. 
- Arities that take a start time are retained to avoid breaking change.
- Eliminated `now+`, a function that scheduled immediate stringed instrument events 21ms in the future. 
Note, the issue that `now+` was dealing with remains - scheduling events too soon results in late warnings. The new `at-offset` checks for events that are <=20ms from now and sends them immediately, with no scheduling, to avoid the warning. `at-offset` is a more appropriate place to deal with that situation than a one-off adjustment in the `stringed` namespace. I would appreciate any feedback or alternative ideas.

Make stringed helpers work with `at`

---

CHANGELOG.md
src/overtone/sc/server.clj
test/overtone/sc/server_test.clj
test/overtone/test_helper.clj

Also reduced the number of dynamic var derefs.

Fix double-eval for `overtone.sc.server/at{-offset}` macros

---

.github/workflows/build.yml
CHANGELOG.md
deps.edn
docs/config.clj
pom.xml
src/overtone/helpers/file.clj
src/overtone/sc/defaults.clj
src/overtone/sc/machinery/server/connection.clj
src/overtone/sc/sclang.clj
src/overtone/sc/synth.clj
test/overtone/sc/sclang_test.clj

Sometimes we want to use a new plugin, package, function or SC Class that's only available in the SuperCollider environment and that would require lots of work to be ported into `overtone`.
This PR gives better support to call `sclang` command (if available) from the REPL while also adding some helpers to convert code to SC's default client lang.
The primary focus for this new effort is in being able to generate a SynthDef easily and reproducible (via caching in generated file) without having to open SC's IDE.
See https://clojurians.slack.com/archives/C053Q1QSG/p1730176977002979 for initial example and discussion.
- With `overtone.sc.sclang/defsynth`, we add the ability to transpile, run `sclang`, save a SynthDef into disk (with metadata), load this SynthDef into `overtone` in one step.
- …

Add `overtone.sc.sclang` ns

---

CHANGELOG.md
src/overtone/inst/synth.clj

As it was, `buzz` would segfault SC, presumably because of integer `envelope` parameter.

Fix `buzz` crashing SC and use parameter `cutoff`

---

CHANGELOG.md
src/overtone/sc/machinery/server/osc_validator.clj

`/cmd` should receive a command name as its first argument, see https://doc.sccode.org/Reference/Server-Command-Reference.html

Fix `/cmd` validation

---

src/overtone/music/pitch.clj

For negative intervals, we can instead ask what the interval for the next octave up is, and subtract 12 from the result. An octave always is an increment of 12, and the number of intervals per octave depends on the length of the SCALE.

Allow negative arguments to nth-interval

---

.github/workflows/build.yml
CHANGELOG.md
src/overtone/inst/synth.clj

`bass` and `grunge-bass` in `overtone.inst.synth` produce three audio channels from their synth algorithms using multi-channel expansion to add some up and down freq detune. The mixer `stereo-inst-mixer` used to mix the output of instruments that generate more than one channel of audio ignores channels other than the first two, it therefore drops the detuned up audio entirely. Also, it uses `balance2` to pan, which means that by default the intended `freq` tone would come from the left channel and the detuned down tone would come from the right channel.
This is broken and not the intention of the `bass` and `grunge-bass` authors. The fix is to mix the three audio paths into one at the end of the instruments' synths.

Mix in detune channels of `bass` and `grunge-bass` to a single instrument channel

---

.gitignore
src/overtone/examples/getting_started/basic.clj

- Move commented out code into comment forms and remove the line comments. This makes it easier to execute the commands when viewing the file.
- The file was playing a white noise sound at load time. Fix this by moving the offending call to (demo) into a comment form, so that it only runs when the user wants it to.
- Remove some tiny bits of unused code.
- Don't redefine metro var. Use a different var for the 2nd metronome.
Also:
- added some vscode related hidden files to .gitignore

Minor tweaks to the basic getting started example file.

---

CHANGELOG.md
deps.edn
src/overtone/helpers/lib.clj
src/overtone/sc/machinery/synthdef.clj
src/overtone/studio/inst.clj
src/overtone/studio/mixer.clj
test/overtone/studio_test.clj

This makes `:group`, `:instance-group`, `:fx-group` and `:mixer` atoms in a `Inst` so we can enable the loading of the insts at anytime, even before the server startup.

Enable insts to be loaded before server startup

---

.github/workflows/build.yml
src/overtone/studio/event.clj
test/overtone/studio/event_test.clj

Questions:
1. ~~Should `padd` also accept `:proto`? And shouldn't the  parameters to `padd` follow the same rules as `presume`, namely, to take their value from `opts`, or from the current player, and lastly a fixed default?~~ `padd` now uses the same option handling.
1. For the test, this PR removed the `^:private` annotation from `pplayers` atom. Should we leave that unchanged and add a `pget` accessor instead?

Pattern lib fixes to `:proto` param and `:clock` consistency

---

src/overtone/studio/inst.clj

Inspired by @jave's [question](https://clojurians.slack.com/archives/C053Q1QSG/p1738800087725859), I started exploring the issue he noticed, that he was not hearing stereo imaging from stereo instruments. It turns out that the stereo mixer as written does not work.
```clojure
;; Current implementation
(defsynth stereo-inst-mixer
[in-bus  10
out-bus 0
volume  DEFAULT-VOLUME
pan     DEFAULT-PAN]
(let [snd  (in in-bus 2)
snd  (select (check-bad-values snd 0 0)
[snd (dc 0) (dc 0) snd])
snd  (limiter snd 0.99 0.001)
sndl (select 0 snd)
sndr (select 1 snd)]
(out out-bus (balance2 sndl sndr pan volume))))))
```
`snd` is two channels, but the channel expansion of `select` results in a 6 channel array. `check-bad-values` outputs an index that requires a length 4 array. The result was that the left …

Fix inst stereo mixer

---

CHANGELOG.md
deps.edn
src/overtone/studio/event.clj
test/overtone/studio/event_test.clj

In order to support both quantization and the ability to start a pattern playing immediately when no other pattern is playing, quantization needs to be relative to the start of the first pattern, _not_ relative to clock/metronome `1` beat.
Therefore, this PR introduces a `:quant-base` key which stores the beat at which a player began playing. When resuming a new player, we now look at all the currently playing sequences and quantize off the one that started earliest.
The change simplifies `quantize-ceil` and `quantize-floor`, because rather than quantizing against an implicit beat `1` start, we use `quant-base`.
Question:
- Tests confirm that `offset` works when zero or greater. @plexus, is it intended that it should ever be negative?

Fix pattern quantization, with tests
