overtone/overtone

- src/overtone/studio/midi.clj
solves https://github.com/overtone/overtone/issues/356
> midi-poly-player ignores unmapped control changes

- src/overtone/examples/midi/keyboard.clj
This is based on some MIDI event-handling code I wrote a while ago.
I thought it would be a useful example to include, as one of the first things I wanted to try out with my MIDI keyboard was the sustain pedal.
> Add MIDI keyboard example demonstrating gate and sustain control

- src/overtone/algo/euclidean_rhythm.clj
- src/overtone/examples/compositions/euclidean_rhythms.clj
- test/overtone/algo/euclidean_rhythm_test.clj
Attempted to add an example to clarify things but happy to defer to your expertise on any edits. I think having this for generating polyrhythms and the like would be a great composition tool for people.
> add euclidean-rhythm algorithm, test, and example

- LICENSE
> Updated the license year

- src/overtone/examples/buses/getonthebus.clj
you're->your && defalt->default. 
I'm going to run through other files some time later.
> correct spelling

- src/overtone/examples/midi/keyboard.clj
I was playing around with my midi controller and could get the pitch-bend controller working. Hope somebody would find this useful.
(Btw. thanks for creating & maintaining Overtone! I love it!)
> Add pitch-bend to midi example

- src/overtone/libs/app_icon.clj
> Fix import syntax error in Clojure 1.10.0

- src/overtone/music/pitch.clj
> Get regex match as character before casting to int

- src/overtone/music/pitch.clj
- test/overtone/music/pitch_test.clj
> fix: dec-last

- src/overtone/music/pitch.clj
> add fb to NOTES

- src/overtone/sc/machinery/ugen/metadata/grain.clj
This ugen seems to have been missing. I had previously opened an issue #469.
> Registers grain-buf ugen

- src/overtone/sc/machinery/server/native.clj
Using the `clj-native` functions directly do not work for "out" arguments like `sound-buffer` in `world-copy-sound-buffer`. So, for this particular case, we are using some low-level functions from the JNA struct instance to obtain the buffer data.
It should fix
https://groups.google.com/g/overtone/c/9rzTi-kcwlA/m/8SX0VY2BAwAJ, now `pscope` and other scope functions work again.
> Fix buffer reading

- src/overtone/samples/freesound.clj
- src/overtone/sc/envelope.clj
Really frustrating to have to copy that every single time
> Save freesound token for later reuse

- src/overtone/examples/getting_started/pragpub_article.clj
- src/overtone/sc/machinery/ugen/metadata/extras/mda.clj
Fix broken freesound link for dirty-kick
Explain how to get mda-piano from sc3-plugins
It took me quite a while to figure this one out, so might help someone else…
> Fixes for pragpub_article

- src/overtone/sc/machinery/ugen/metadata/extras/stk.clj
Docs: https://doc.sccode.org/Classes/StkBeeThree.html
> Fix stk-bee-three arg names

- src/overtone/sc/machinery/ugen/metadata/delay.clj
- src/overtone/sc/machinery/ugen/metadata/noise.clj
- src/overtone/sc/machinery/ugen/metadata/osc.clj
Resolve https://github.com/overtone/overtone/issues/526
> Remove ignored mul & add parameters

- CHANGELOG.md
- src/overtone/samples/freesound.clj
Refresh the access-token if it has expired, otherwise tokens are only valid for ~2 hours it seems.
> Handle freesound refresh tokens

- src/overtone/music/pitch.clj
- test/overtone/music/pitch_test.clj
Close https://github.com/overtone/overtone/issues/548
> `scale-field` should use first octave & return valid notes

- src/overtone/samples/freesound.clj
I don't know how but I think I had a freesound access token but no refresh token. In this case, `refresh-token!` threw an uncaught IOException (probably due to a `nil` request param) and (permanently?) interrupted the flow.
This can be tested by making a bogus access token and removing the refresh token:
```
;; destroy access token
(swap! *access-token* (fn [%] (str (char (inc (int (nth % 0)))) (subs % 1))))
;; delete refresh token
(swap! config/live-store dissoc :freesound-refresh-token))
;; download something from freesound...
--> Asset not cached - starting download...
--> Downloading file (58 B) - https://freesound.org/apiv2/sounds/148492/download/
Freesound access token has expired, but no refresh token present. Asking for a new access token.
Authorize in browser and paste code in …
```
> Don't refresh missing refresh_token

- src/overtone/music/pitch.clj
- test/overtone/music/pitch_test.clj
> Return entire scale regardless of length

- CHANGELOG.md
- src/overtone/helpers/lib.clj
- test/overtone/sc/envelope_test.clj
> add line numbers for defunk ops

- src/overtone/sc/synth.clj
We aren't restricted to file paths only when loading a external synthdef, we can also use URL or byte arrays as `synthdef-read` has support for these already.
> Add support for URL and byte arrays in `synth-load`

- CHANGELOG.md
- src/overtone/studio/mixer.clj
Studio groups depend on foundational root group.
> Setup studio groups only after foundational groups

- .github/workflows/build.yml
- CHANGELOG.md
- docs/config.clj
- src/overtone/helpers/file.clj
- src/overtone/sc/defaults.clj
- src/overtone/sc/machinery/server/connection.clj
- src/overtone/sc/sclang.clj
- src/overtone/sc/synth.clj
- test/overtone/sc/sclang_test.clj
> add sclang unit test

- .gitignore
- CHANGELOG.md
- src/overtone/sc/machinery/server/connection.clj
Close #573 
Related https://github.com/supercollider/supercollider/issues/1022
> reduce likelihood of choosing a used random port for `scsynth`

- src/overtone/sc/sclang.clj
Add explanation where scd files wind up
> Small doc improvement for sclang.clj

- .github/workflows/build.yml
We get 1-2 minutes for free by incorporating https://github.com/DeLaGuardo/setup-clojure/pull/109
Seems to complete in 1m 45s end-to-end.
> Improve build performance
